### ISSUE TITLE
On Some Urls receive "[error] SSL: :certify: ssl_handshake.erl:1592:Fatal error: bad certificate"

### ISSUE THREAD

**Issue by Faolain** [appunite/link_preview_generator#17]
For some urls such as the following link, https://plato.stanford.edu/entries/consciousness-higher/ the error [error] SSL: :certify: ssl_handshake.erl:1592:Fatal error: bad certificate is returned. Any idea what this could be or how to solve it?

**Comment by amatalai** [comment]
Hi, I'm unable to reproduce this error.
Please provide full stacktrace, elixir/erlang versions and anything that could lead me to the right direction.

**Comment by Faolain** [comment]
Sure, below is the error and corresponding versions


<img width="759" alt="screen shot 2017-05-27 at 6 48 37 pm" src="https://cloud.githubusercontent.com/assets/9613083/26524795/c4c78bd6-430d-11e7-904f-22829b24b27b.png">

LinkPreviewGenerator version: "0.0.5"
Elixir 1.3.4
OTP Version 19
Erlang Version 8.1

**Comment by amatalai** [comment]
Oh, now I see where problem is.

LinkPreviewGenerator was depracated in favor of LinkPreview. It:
- is more stable (we use it on production)
- has shorter name (yay)
- is backed by Tesla (more flexible http client)
- version 1.0.0 (no breaking changes until v2)

**Comment by amatalai** [comment]
@Faolain did upgrade help?

**Comment by Exadra37** [comment]
> is backed by Tesla (more flexible http client)

More flexible and more insecure:

```
iex> LinkPreview.create "https://badssl.com" 
{:ok,
 %LinkPreview.Page{
   description: "🎛Dashboard",
   images: [%{url: "front-page-icons/chrome.svg"}],
   original_url: "https://badssl.com",
   title: "badssl.com",
   website_url: "badssl.com"
 }}
```

That request should fail, because the website returns a bad ssl certificate.

You can read more about why in the issue I open 2 years ago in Tesla, that continues open, therefore not fixed, that causes libraries like yours to be accidentally insecure by default:

https://github.com/teamon/tesla/issues/293
